FROM public.ecr.aws/l1s7l7p8/all-in-one-ai-stable-diffusion-webui-training:latest

COPY train.py /opt/ml/code
COPY stable-diffusion-webui /opt/ml/code/

RUN git clone https://github.com/xieyongliang/sd_dreambooth_extension.git /opt/ml/code/extensions/sd_dreambooth_extension
RUN . /opt/ml/code/venv/bin/activate && pip install boto3